name: Mi primer workflow
on:
  push:
    branches: [master]
jobs:
  Mi-primer-job:
    name: Mi primer job
    runs-on: ubuntu-latest
  steps:
    - name: Imprimir
      id: imprimir
      env:
        MI_VARIABLE: Hola munod
      run:
        echo $MI_VARIABLE